import os
import shutil
import tempfile
from typing import Optional, List
from huggingface_hub import HfApi, CommitOperationAdd, snapshot_download
import logging


class GitOperations:
    def __init__(self, token: Optional[str] = None):
        self.logger = logging.getLogger(__name__)
        self.repo_path = None
        self.token = token
        self.hf_api = HfApi(token=token)

    def download_repo(self, repo_id: str) -> str:
        """Download a repository from Hugging Face Hub to a temporary working directory"""
        import tempfile
        import shutil
        
        try:
            self.logger.info(f"Downloading {repo_id}")
            
            # Use HF Hub's snapshot_download to get repository files (cached)
            cached_repo_path = snapshot_download(
                repo_id=repo_id,
                token=self.token,
                repo_type="model"
            )
            
            # Create a temporary working directory
            temp_dir = tempfile.mkdtemp(prefix=f"transformersjs_migration_{repo_id.replace('/', '_')}_")
            
            # Copy cached repository to temporary directory for manipulation
            for item in os.listdir(cached_repo_path):
                src_path = os.path.join(cached_repo_path, item)
                dst_path = os.path.join(temp_dir, item)
                
                if os.path.isdir(src_path):
                    shutil.copytree(src_path, dst_path)
                else:
                    shutil.copy2(src_path, dst_path)
            
            self.repo_path = temp_dir
            self.logger.info(f"Downloaded {repo_id} to cache and copied to working directory: {temp_dir}")
            return temp_dir
        except Exception as e:
            self.logger.error(f"Failed to download {repo_id}: {e}")
            raise

    def upload_changes(self, repo_path: str, repo_id: str, migration_type_name: str, 
                      migration_title: str, migration_description: str, 
                      modified_files: List[str]) -> bool:
        """Upload changes to the repository using HF Hub API
        
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            if not modified_files:
                self.logger.info(f"No files to upload for {repo_id}")
                return False
            
            # Create branch name for specific migration type
            branch_name = f"transformersjs-v3-{migration_type_name}"
            self.logger.info(f"Creating commit on branch {branch_name}")
            
            # Prepare commit operations for modified files
            operations = []
            for file_path in modified_files:
                local_file_path = os.path.join(repo_path, file_path)
                if os.path.exists(local_file_path):
                    operations.append(
                        CommitOperationAdd(
                            path_in_repo=file_path,
                            path_or_fileobj=local_file_path
                        )
                    )
                    self.logger.info(f"Prepared upload for {file_path}")
            
            if not operations:
                self.logger.info(f"No valid files to upload for {repo_id}")
                return False
            
            # Create commit message
            commit_message = f"""{migration_title}

{migration_description}

Generated by transformers-js-v3-migrator"""
            
            # Create commit on new branch (HF will create the branch from default branch automatically)
            commit_info = self.hf_api.create_commit(
                repo_id=repo_id,
                operations=operations,
                commit_message=commit_message,
                create_pr=False,  # We'll create PR separately
                revision=branch_name,
                repo_type="model"
                # No parent_commit specified - HF Hub will use repository's default branch
            )
            
            self.logger.info(f"Successfully uploaded changes to {repo_id} on branch {branch_name}")
            self.logger.info(f"Commit URL: {commit_info.commit_url}")
            
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to upload changes for {repo_id}: {e}")
            raise

    def create_pull_request(self, repo_id: str, pr_title: str, pr_description: str, 
                           migration_type_name: str) -> Optional[str]:
        """Create a pull request using HF Hub API
        
        Returns:
            str: PR URL if successful, None otherwise
        """
        try:
            branch_name = f"transformersjs-v3-{migration_type_name}"
            
            # Use create_commit with create_pr=True to create a pull request
            # We need to create an empty commit operation just to trigger PR creation
            # Since we already uploaded the files, we can use an empty operations list
            
            # Alternative approach: Create a discussion that references the branch
            discussion_description = f"""{pr_description}

**Branch:** `{branch_name}`
**Changes:** Please review the changes in the `{branch_name}` branch and merge if they look correct.

You can view the changes at: https://huggingface.co/{repo_id}/commit/{branch_name}"""

            discussion = self.hf_api.create_discussion(
                repo_id=repo_id,
                title=pr_title,
                description=discussion_description,
                repo_type="model"
            )
            
            pr_url = f"https://huggingface.co/{repo_id}/discussions/{discussion.num}"
            self.logger.info(f"Created discussion/PR: {pr_url}")
            
            return pr_url
            
        except Exception as e:
            self.logger.error(f"Failed to create PR for {repo_id}: {e}")
            # Return a fallback URL for manual PR creation
            return f"https://huggingface.co/{repo_id}/discussions/new"

    def cleanup_temp_directory(self, temp_path: str):
        """Clean up temporary working directory"""
        if not temp_path or not os.path.exists(temp_path):
            return
            
        try:
            import shutil
            shutil.rmtree(temp_path)
            self.logger.info(f"Cleaned up temporary directory: {temp_path}")
        except Exception as e:
            self.logger.warning(f"Failed to cleanup temporary directory {temp_path}: {e}")

